### ISSUE TITLE
Can't seem to login as Gamemaster, blank password does not work. 

### ISSUE THREAD

**Issue by develroo** [chrisesharp/foundryvtt-owb-ponteville#1]
I tried to reset it from the Setup menu. It says it resets it, but a blank one still does not work. 

```
FoundryVTT | 2023-04-12 18:27:50 | [info] Software license verification succeeded
FoundryVTT | 2023-04-12 18:27:50 | [info] Requesting UPnP port forwarding to destination port 30000
FoundryVTT | 2023-04-12 18:27:52 | [info] Server started and listening on port 30000
FoundryVTT | 2023-04-12 18:28:00 | [info] Created client session 201fe79776a4b234386b3b3b
FoundryVTT | 2023-04-12 18:28:11 | [info] Administrator authentication successful for session 201fe79776a4b234386b3b3b
FoundryVTT | 2023-04-12 18:28:41 | [info] Resetting all user access keys in World owb-ponteville-bridge
FoundryVTT | 2023-04-12 18:28:57 | [warn] User authentication failed for user Gamemaster; invalid password

```

For reference, I am on 

Fvtt Version 10 - Build 291
WWII:OWB 1.2.1
Ponteville Bridge 1.0.2

How do I go about debugging what is wrong ?

Thanks.

**Comment by chrisesharp** [comment]
Hmm, this is odd...not sure how this has crept in, and I have no idea why Foundry couldn't correctly reset it. 

As a local fix, you can delete the user database from the world directory on your server -  `worlds/owb-ponteville-bridge/data/users.db` - before starting the world. Foundry will create a fresh new one with a passwordless Gamemaster id.

**Comment by chrisesharp** [comment]
Fixed zip file now so fresh installs will work.

**Comment by develroo** [comment]
Yup.. Fixed. Thanks!
